#pragma once

#include "../../Common.h"

#define EU_INVALID_ASSET_TYPE_ID 0
#define EU_DEFAULT_ASSET_TYPE_ID 1

#define EU_INVALID_MATERIAL_ID				EU_INVALID_ASSET_TYPE_ID
#define EU_INVALID_MATERIAL_MODIFIER_ID		EU_INVALID_ASSET_TYPE_ID
#define EU_INVALID_MODEL_ID					EU_INVALID_ASSET_TYPE_ID

#define EU_DEFAULT_MATERIAL_ID				EU_DEFAULT_ASSET_TYPE_ID
#define EU_DEFAULT_MATERIAL_MODIFIER_ID		EU_DEFAULT_ASSET_TYPE_ID
#define EU_DEFAULT_MODEL_ID					EU_DEFAULT_ASSET_TYPE_ID

namespace Eunoia {

	enum PresetSamplerID
	{
		EU_SAMPLER_NEAREST_REPEAT_AF = 4,
		EU_SAMPLER_NEAREST_CLAMP_TO_EDGE_AF,
		EU_SAMPLER_LINEAR_CLAMP_TO_EDGE_AF,
		EU_SAMPLER_LINEAR_REPEAT_AF,

		EU_SAMPLER_NEAREST_REPEAT,
		EU_SAMPLER_NEAREST_CLAMP_TO_EDGE,
		EU_SAMPLER_LINEAR_CLAMP_TO_EDGE,
		EU_SAMPLER_LINEAR_REPEAT,

		NUM_PRESET_SAMPLERS
	};

	enum PresetTextureID
	{
		EU_TEXTURE_WHITE_4x4,
		EU_TEXTURE_BLACK_4x4,

		NUM_PRESET_TEXTURES
	};

	enum PresetModelID
	{
		EU_MODEL_CUBE_ID = EU_DEFAULT_MODEL_ID,
		EU_MODEL_SPHERE_ID,
		EU_MODEL_PLANE_ID,
	};

	typedef u32 AssetTypeID;
	typedef AssetTypeID MaterialID;
	typedef AssetTypeID MaterialModifierID;
	typedef AssetTypeID ModelID;

}